apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gc-agents-daemonset
  namespace: {{ .Values.gcNamespace | default .Values.global.gcNamespace}}
  labels:
    app: guardicore-agent
spec:
  selector:
      matchLabels:
        app: guardicore-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: guardicore-agent
      annotations:
        guardicore/enforcement: {{ .Values.global.enforcementCni }}
        {{- with .Values.global.annotations  }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
        {{- with .Values.annotations  }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
    spec:
      tolerations:
      {{- with .Values.tolerations  }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      # Rancher taints
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
        operator: Equal
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"
        operator: Equal
      # k8s 1.24 taints
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      # k8s OCP infra node taints
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      # Azure cni agent pool nodes taints
      - effect: NoSchedule
        key: CriticalAddonsOnly
        value: "true"
        operator: Equal
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Values.gcServiceAccount | default .Values.global.gcServiceAccount}}
      imagePullSecrets:
      {{- if .Values.registryAuthFile | default .Values.global.registryAuthFile }}
        - name: guardicore-registry-secret
      {{- end -}}
      {{- with .Values.global.imagePullSecrets }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: guardicore-agent
        image: {{ include "privateRegistry" . }}gc-guest-agent:{{ .Values.appVersion | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env:
          - name: UI_UM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guardicore-ui-secret
                key: installation_password
          - name: AGENT_HOST_PATH
            value: "/host"
          - name: SSL_SERVER
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: sslServer
          - name: SSL_ADDRESSES
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: sslAddresses
          - name: SSL_PORT
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: sslPort
          - name: GC_PROFILE
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: gcProfile
          - name: ENFORCEMENT_CNI
            value: {{ .Values.global.enforcementCni }}
          - name: LOG_VERDICT
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: logVerdict
          - name: GC_CONTAINER_MODE
            value: "native"
          - name: VERBOSE
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: debug
          - name: DAEMON_ARGS
            {{ if .Values.debug }}
            value: "--verbose {{ .Values.daemonArgs  }}" 
            {{ else }}
            value: "{{ .Values.daemonArgs  }}"
            {{ end }}
          - name: CURRENT_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GC_NOTIFICATION_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: GC_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ENABLE_GC_INIT_INJECTION
            value: "false"
          - name: RETENTION_THRESHOLD_VAL
            valueFrom:
              configMapKeyRef:
                name: guardicore-config
                key: retentionThreshold
          - name: GC_CONTAINER_RUNTIME_PATH
            value: {{ .Values.containerRuntimePath }}
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        securityContext:
          privileged: true
          capabilities:
            add: [ "SYS_ADMIN" ]
        volumeMounts:
          - name: var-log
            mountPath: /var/log
          - name: boot
            mountPath: /boot
            readOnly: true
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: lib-modules
            mountPath: /host/lib/modules
            readOnly: true
          - name: dev
            mountPath: /host/dev
          - name: etc
            mountPath: /host/etc
          - name: var-run
            mountPath: /host/var/run
          - name: host-log
            mountPath: /host/var/log
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/gc-package-ctrl" , "uninstall"]
      volumes:
        - name: var-log
          hostPath:
            path: /var/log/guardicore
        - name: boot
          hostPath:
            path: /boot
        - name: proc
          hostPath:
            path: /proc
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: etc
          hostPath:
            path: /etc
        - name: var-run
          hostPath:
            path: /var/run
        - name: host-log
          hostPath:
            path: /var/log
