apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: gc-agent-role
  namespace: {{ .Values.gcNamespace | default .Values.global.gcNamespace}}
rules:
# RO permissions
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
# RW permissions
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
