apiVersion: v1
kind: Secret
metadata:
  name: gc-secret
  namespace: {{ .Values.orchNamespace }}
  annotations:
    kubernetes.io/service-account.name: gc-reader
type: kubernetes.io/service-account-token
