apiVersion: v1
kind: ServiceAccount
metadata:
  name: gc-reader
  namespace: {{ .Values.orchNamespace  }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gc-cluster-reader
rules:
  - apiGroups: [""]
    resources:
      - events
      - nodes
      - services
      - namespaces
      - replicationcontrollers
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources:
      - "services"
      - "configmaps"
    verbs: ["get", "list", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - replicasets.apps
      - replicasets.apps/scale
      - daemonsets
      - daemonsets.apps
      - deployments
      - deployments.apps
      - deployments.apps/scale
      - statefulsets
      - statefulsets.apps
      - statefulsets.apps/scale
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - jobs.batch
      - cronjobs
      - cronjobs.batch
    verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gc-cluster-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: gc-reader
    namespace: {{ .Values.orchNamespace  }}
roleRef:
  kind: ClusterRole
  name: gc-cluster-reader
  apiGroup: rbac.authorization.k8s.io
