{{- include "validatePrerequisites" . }}

---
{{- if and (.Values.global.registryAuthFile) (not (empty .Values.global.registryAuthFile)) }}
apiVersion: v1
kind: Secret
metadata:
  name: guardicore-registry-secret
  namespace: {{ .Values.global.gcNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.global.registryAuthFile | toString |trim | b64enc }}"
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: guardicore-cas-chain-secret
  namespace: {{ .Values.global.gcNamespace }}
type: Opaque
data:
  guardicore_cas_chain_file.pem: "{{ .Values.caCertFile | trim | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: guardicore-ui-secret
  namespace: {{ .Values.global.gcNamespace }}
type: Opaque
stringData:
  installation_password: "{{ .Values.uiUmPassword }}"